# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 538f5b5369bda8cf1d95ea44ffbcf9d6f79ebe597e4ae6832b55461effbd3d10c947ecfa6066f7c6ee193abda0e6644c971e518123095a8a0ad4afc27f89edbe

test:
  secret_key_base: aac441fd27952cd0d04b122af200dcafb1850c06d7b040abea76fd4294fa96822ce2875d44f8409c6114dcf0bb89eda10c43999545a0b460a1a4892837798622

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
